version: '2'
services:
    maventest-app:
        image: maventest
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://maventest-mysql:3306/maventest?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    maventest-mysql:
        extends:
            file: mysql.yml
            service: maventest-mysql
